language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2.0
  - 2.3.0
  - 2.4.0

notifications:
  email:
    on_success: never

install: gem install bundler culqi-ruby

script: bundle exec rake test

sudo: false
